# Generated by scripts/release/generate-homebrew-casks.mjs. Do not edit manually.

cask "mochi-desktop" do
  version "0.5.1"

  on_arm do
    sha256 "57330f38ffcb3dd97a924ff6291aa40c8a16177064a2c3c68842ee3b51a3aca6"
    url "https://github.com/BrainerVirus/mochi/releases/download/v0.5.1/Mochi_0.5.1_aarch64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  on_intel do
    sha256 "a997b1c6ec3c6373b433c590312dbdde258a86c61b85eff8af5cadfd3b084307"
    url "https://github.com/BrainerVirus/mochi/releases/download/v0.5.1/Mochi_0.5.1_x64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  name "Mochi"
  desc "Cross-platform desktop companion for AI coding tool usage"
  homepage "https://github.com/BrainerVirus/mochi"

  app "Mochi.app"
end
