# Generated by scripts/release/generate-homebrew-casks.mjs. Do not edit manually.

cask "mochi-unstable" do
  version "unstable-20260624.211640"

  on_arm do
    sha256 "0481c63c46ead5bb3c4f1b8fa152af24707a00f163f3105a23e94db00c05c3ea"
    url "https://github.com/BrainerVirus/mochi/releases/download/unstable-20260624.211640/Mochi_0.2.6_aarch64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  on_intel do
    sha256 "e75d755b5288db0c92abe914a0c3c6c64146dda36966698ff7b5dda094c0f2d7"
    url "https://github.com/BrainerVirus/mochi/releases/download/unstable-20260624.211640/Mochi_0.2.6_x64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  name "Mochi (Unstable)"
  desc "Cross-platform desktop companion for AI coding tool usage (unstable channel)"
  homepage "https://github.com/BrainerVirus/mochi"

  app "Mochi.app"
end
