# Generated by scripts/release/generate-homebrew-casks.mjs. Do not edit manually.

cask "mochi-desktop" do
  version "0.5.0"

  on_arm do
    sha256 "6e9d7192fe37f0343f60f284500576602fea507964b37eb461cee8d341caa7e1"
    url "https://github.com/BrainerVirus/mochi/releases/download/v0.5.0/Mochi_0.5.0_aarch64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  on_intel do
    sha256 "66abfd5b072cc501b5d7f2aba2bffe3fa08cdd1e26e9b7b193f2718a71016a22"
    url "https://github.com/BrainerVirus/mochi/releases/download/v0.5.0/Mochi_0.5.0_x64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  name "Mochi"
  desc "Cross-platform desktop companion for AI coding tool usage"
  homepage "https://github.com/BrainerVirus/mochi"

  app "Mochi.app"
end
