# Generated by scripts/release/generate-homebrew-casks.mjs. Do not edit manually.

cask "mochi-unstable" do
  version "unstable-20260624.210511"

  on_arm do
    sha256 "b5fd57bc439c68b9a64269bc7a247dbfce186e63997d1300b8e0f688b2645870"
    url "https://github.com/BrainerVirus/mochi/releases/download/unstable-20260624.210511/Mochi_0.2.6_aarch64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  on_intel do
    sha256 "06588959209ad5826cf0037b0b96aab166063bf939e5807b7d8e9a17e65a34b2"
    url "https://github.com/BrainerVirus/mochi/releases/download/unstable-20260624.210511/Mochi_0.2.6_x64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  name "Mochi (Unstable)"
  desc "Cross-platform desktop companion for AI coding tool usage (unstable channel)"
  homepage "https://github.com/BrainerVirus/mochi"

  app "Mochi.app"
end
