# Generated by scripts/release/generate-homebrew-casks.mjs. Do not edit manually.

cask "mochi-unstable" do
  version "unstable-20260621.225155"

  on_arm do
    sha256 "f291ec19dbdeec5ba19e73536777d24cd2ecd7cd6d5e3c355f80e9d4dbb8ab4d"
    url "https://github.com/BrainerVirus/mochi/releases/download/unstable-20260621.225155/Mochi_0.2.4_aarch64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  on_intel do
    sha256 "97801294d56efee60fc1518b0916e65f6c2a6341ec54e91e7e9fd9430cb3a3af"
    url "https://github.com/BrainerVirus/mochi/releases/download/unstable-20260621.225155/Mochi_0.2.4_x64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  name "Mochi (Unstable)"
  desc "Cross-platform desktop companion for AI coding tool usage (unstable channel)"
  homepage "https://github.com/BrainerVirus/mochi"

  app "Mochi.app"
end
