# Generated by scripts/release/generate-homebrew-casks.mjs. Do not edit manually.

cask "mochi-desktop" do
  version "0.2.5"

  on_arm do
    sha256 "1df720be8e5eee06dcb2866ab43a883c147c53a577a71bdafc230fe6866c16aa"
    url "https://github.com/BrainerVirus/mochi/releases/download/v0.2.5/Mochi_0.2.5_aarch64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  on_intel do
    sha256 "5692c6e6daa7476948d7d3be50ffac2c3a6411f2184fd7b039165dc175886c77"
    url "https://github.com/BrainerVirus/mochi/releases/download/v0.2.5/Mochi_0.2.5_x64.dmg",
        verified: "github.com/BrainerVirus/mochi/"
  end

  name "Mochi"
  desc "Cross-platform desktop companion for AI coding tool usage"
  homepage "https://github.com/BrainerVirus/mochi"

  app "Mochi.app"
end
